---  
- hosts: localhost  
  connection: local  
  gather_facts: no  
  vars_files:
    # - amazon_ami_info  
    - odx_vpc_info
    - redhat_ami_info  
  vars:  
    instance_type: t2.micro
    region: us-east-1    
    group: odx_sg_webserver
    keyname: odx_key
    ami: "{{ us_east_1 }}"
    subnet_web: "{{ odx_subnet_public_0 }}"
  tasks:  
    # - debug: msg="{{ ami }}"
    - name: EC2 basic provisioning  
      ec2:
        key_name: "{{ keyname }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: yes
        group: "{{ group }}"
        count: 1
        vpc_subnet_id: "{{ subnet_web }}"
        region: "{{ region }}"
        # assign_public_ip: yes
        instance_tags:  
          Name: odx_web2
          class: webserver  
          environment: dev          
  # roles:
  #   -  ansible  